# Generated by Django 5.1.1 on 2024-10-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innhome_app', '0003_remove_propiedad_imagenes_imagenpropiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='num_banos',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='num_habitaciones',
            field=models.IntegerField(default=1),
        ),
    ]
