# Generated by Django 5.1.1 on 2024-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innhome_app', '0005_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(),
        ),
    ]
